name: Release
on:
  push:
    branches:
      - "main"
      
jobs:
  semantic-release:
    name: Release the application
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permit release creation
      issues: write # Write on released issues
      pull-requests: write # Write on released PRs
      actions: write # Trigger deploy action
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install Semantic Release globally
        run: npm install -g semantic-release @semantic-release/git @semantic-release/exec @semantic-release/changelog

      # Semantic Release configuration executes gh CLI which triggers the deploy workflow
      - name: Release with semantic versioning
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
